#!/usr/bin/env python2.7

import logging

import ma.config.log
import ma.api.product
import ma.progress

_LOGGER = logging.getLogger(__name__)

def _main():
    ma.config.log.configure(False)

    pa = ma.api.product.ProductApi()
    
    products = pa.get_list()
    products = list(products)

    progress = ma.progress.Progress(len(products), 10)

    for p in products:
        sku = p['sku']

        _LOGGER.info("Deleting: [%s]", sku)
        pa.delete_with_sku(sku)

        progress.tick()

if __name__ == '__main__':
    _main()
